version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins2
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-net
    restart: unless-stopped

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube2
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - dev-net
    restart: unless-stopped

  api:
    build: ./api  # Chemin vers le dossier contenant le Dockerfile de ton API
    container_name: flask-api2
    ports:
      - "5000:5000"
    networks:
      - dev-net
    restart: unless-stopped
    depends_on:
      - sonarqube

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  dev-net:

